#!/usr/bin/env sh
# Validate a commit message against the standard in docs/commit-messages.md.
#
# Usage:
#   scripts/validate-commit-msg.sh <commit-msg-file>
#   git log -1 --format=%B <sha> | scripts/validate-commit-msg.sh -
#
# Exits 0 when the message conforms (or is an exempt merge/revert/fixup/squash
# commit), and non-zero with an actionable message on stderr otherwise.
set -eu

# Resolve $0 through any symlinks so the script finds its siblings when it is
# installed as .git/hooks/commit-msg.
cm_self=$0
while [ -L "$cm_self" ]; do
	cm_link=$(readlink "$cm_self")
	case "$cm_link" in
	/*) cm_self=$cm_link ;;
	*) cm_self=$(dirname -- "$cm_self")/$cm_link ;;
	esac
done
SCRIPT_DIR=$(CDPATH='' cd -- "$(dirname -- "$cm_self")" && pwd)
# shellcheck source=scripts/commit-msg-lib.sh
. "$SCRIPT_DIR/commit-msg-lib.sh"

MSG_FILE=${1:-}
if [ -z "$MSG_FILE" ]; then
	echo "usage: $(basename "$0") <commit-msg-file|->" >&2
	exit 2
fi

CLEANUP=""
if [ "$MSG_FILE" = "-" ]; then
	CLEANUP="${TMPDIR:-/tmp}/commit-msg-stdin.$$"
	cat >"$CLEANUP"
	MSG_FILE=$CLEANUP
elif [ ! -f "$MSG_FILE" ]; then
	echo "$(basename "$0"): no such file: $MSG_FILE" >&2
	exit 2
fi

finish() {
	[ -n "$CLEANUP" ] && rm -f "$CLEANUP"
	return 0
}
trap finish EXIT

fail() {
	echo "commit message rejected: $1" >&2
	shift
	for hint in "$@"; do
		echo "  $hint" >&2
	done
	echo "" >&2
	echo "  subject: $SUBJECT" >&2
	echo "  see docs/commit-messages.md, or bypass with: git commit --no-verify" >&2
	exit 1
}

COMMENT_CHAR=$(cm_comment_char)
SUBJECT_LINE=$(cm_subject_lineno "$MSG_FILE" "$COMMENT_CHAR")

if [ "$SUBJECT_LINE" -eq 0 ]; then
	SUBJECT="(empty)"
	fail "the message is empty" \
		"write a subject in the form: type(scope): description"
fi

SUBJECT=$(sed -n "${SUBJECT_LINE}p" "$MSG_FILE")

# Merge, revert, fixup, squash and amend commits are generated by git itself
# and are exempt from the standard.
cm_is_exempt "$SUBJECT" && exit 0

case "$SUBJECT" in
*:*) ;;
*)
	fail "no type prefix" \
		"expected 'type: description', e.g. 'fix: guard against a nil provider'" \
		"allowed types: $CM_TYPES"
	;;
esac

PREFIX=${SUBJECT%%:*}
DESC=${SUBJECT#*:}

if ! printf '%s' "$PREFIX" | grep -Eq '^[a-z]+(\([a-z0-9._/-]+\))?!?$'; then
	fail "malformed type prefix '$PREFIX'" \
		"expected lowercase 'type', 'type(scope)', 'type!' or 'type(scope)!'" \
		"allowed types: $CM_TYPES"
fi

TYPE=$(cm_type_of "$SUBJECT")
if ! cm_is_known_type "$TYPE"; then
	fail "unknown type '$TYPE'" \
		"allowed types: $CM_TYPES"
fi

if [ -z "$(printf '%s' "$DESC" | tr -d '[:space:]')" ]; then
	fail "empty description" \
		"describe the change in the imperative mood, e.g. '$TYPE: add a retry budget'"
fi

case "$DESC" in
" "*) ;;
*)
	fail "missing space after the colon" \
		"write '$TYPE: <description>', not '$TYPE:<description>'"
	;;
esac

DESC=${DESC# }
case "$DESC" in
" "*)
	fail "more than one space after the colon" \
		"write '$TYPE: <description>' with exactly one space"
	;;
esac

case "$DESC" in
*.)
	fail "the subject ends with a period" \
		"drop the trailing '.' — subjects are titles, not sentences"
	;;
esac

# GitHub appends " (#123)" to the subject when it squash-merges a pull request,
# which can push an otherwise fine subject over the limit. Authors never type
# it, so it is excluded from the measurement — this only matters when the
# validator is run over already-merged history.
MEASURED=$(printf '%s' "$SUBJECT" | sed -E 's/ \(#[0-9]+\)$//')
LEN=$(printf '%s' "$MEASURED" | awk '{ print length($0) }')
if [ "$LEN" -gt "$CM_MAX_SUBJECT" ]; then
	fail "subject is $LEN characters (limit is $CM_MAX_SUBJECT)" \
		"shorten the subject and move the detail into the body"
fi

# A body, when present, must be separated from the subject by a blank line so
# that git, GitHub and `git log --oneline` all agree on where the subject ends.
SECOND=$(sed -n "$((SUBJECT_LINE + 1))p" "$MSG_FILE")
if [ -n "$SECOND" ]; then
	case "$SECOND" in
	"$COMMENT_CHAR"*) ;;
	*)
		fail "no blank line between the subject and the body" \
			"leave line $((SUBJECT_LINE + 1)) blank before the body starts"
		;;
	esac
fi

exit 0
